version: '3.4'

services:
  tomcat:
    image: tomcat
    ports:
      - 8888:8888
      - 8081:8080
    volumes:
      - ..\tomcat\webapps:/usr/local/tomcat/webapps
  jenkins:
    image: jenkins/jenkins
    user: root
    ports:
      - 8080:8080
    volumes:
    - ..\jenkins:/var/jenkins_home
    - ..\tomcat\webapps\IgalNisanDanielNissim:/var/jenkins_home/workspace/PullClient/build